# nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-bridge
  namespace: timescale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80  # NGINX listens on port 80

