apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: chirpstack-rest-api
  name: chirpstack-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-rest-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: chirpstack-rest-api
    spec:
      containers:
        - args:
            - --server
            - chirpstack:8080
            - --bind
            - 0.0.0.0:8090
            - --insecure
          image: chirpstack/chirpstack-rest-api:4
          name: chirpstack-rest-api
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
