apiVersion: v1
data:
  chirpstack-gateway-bridge-basicstation-us915_0.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_0/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_0/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_0/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_1.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_1/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_1/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_1/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_2.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_2/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_2/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_2/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_3.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_3/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_3/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_3/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_4.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_4/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_4/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_4/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_5.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_5/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_5/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_5/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_6.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_6/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_6/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_6/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge-basicstation-us915_7.toml: |-
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

    [integration.mqtt]
    event_topic_template="us915_7/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="us915_7/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="us915_7/gateway/{{ .GatewayID }}/command/#"

    [backend]
    type="semtech_udp"

      # Semtech UDP packet-forwarder backend.
      [backend.semtech_udp]

      # ip:port to bind the UDP listener to
      #
      # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
      # This is the listener to which the packet-forwarder forwards its data
      # so make sure the 'serv_port_up' and 'serv_port_down' from your
      # packet-forwarder matches this port.
      udp_bind = "0.0.0.0:1700"

      # Skip the CRC status-check of received packets
      #
      # This is only has effect when the packet-forwarder is configured to forward
      # LoRa frames with CRC errors.
      skip_crc_check = false

      # Fake RX timestamp.
      #
      # Fake the RX time when the gateway does not have GPS, in which case
      # the time would otherwise be unset.
      fake_rx_time=false
  chirpstack-gateway-bridge.toml: |
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [general]
    log_level=5

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: chirpstack-gateway-bridge
  name: chirpstack-gateway-bridge-cm0
