apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
spec:
  selector:
    io.kompose.service: postgres
  ports:
    - protocol: TCP
      port: 5432           # The port on which the service will be exposed
      targetPort: 5432      # The PostgreSQL container's port
  type: ClusterIP           # Exposes the service only within the cluster (default behavior)