apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: default
spec:
  type: kv-v2

  # mount path
  mount: secret

  # path of the secret
  path: dev-postgresdb-creds

  # dest k8s secret
  destination:
    name: dev-postgresdb-creds
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth