apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: dirc/devwebapp-ruby:latest
      env:
      - name: EXTERNAL_VAULT_ADDR
        value: "167.172.10.0"
      - name: VAULT_ADDR
        value: "http://$(EXTERNAL_VAULT_ADDR):8200"
      - name: VAULT_TOKEN
        value: root