apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: chirpstack
  name: chirpstack
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: chirpstack
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack
          env:
            - name: MQTT_BROKER_HOST
              value: mosquitto
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: dev-postgresdb-creds
                  key: connection_string
          image: chirpstack/chirpstack:4
          name: chirpstack
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: chirpstack-cm0
            - mountPath: /opt/lorawan-devices
              name: chirpstack-claim1
            - name: pg-cert
              mountPath: /etc/ssl/certs/postgresql-ca.crt
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: chirpstack-cm0
          name: chirpstack-cm0
        - name: chirpstack-claim1
          persistentVolumeClaim:
            claimName: chirpstack-claim1
        - name: pg-cert
          secret:
            secretName: postgresql-ca
